version: '3.8'

services:
  superagent:
    build: .
    container_name: incon_superagent
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    volumes:
      - ./data:/app/data
      - ./.env:/app/.env:ro
      - /:/host

